# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7aa3b47df1c363f464efdecd8a363b7213485f0a80a2c6c383e0cfdc36b3d213af515b24c648537b534ec407c52a8ef6e671c61c20f746ed59c687b5e2bd41e

test:
  secret_key_base: b5f42eafcbdff18d33edbe6bc77dcaca0d1a5b69584c21ae6e76529c6ba052c19ce52fd43077770db0c34e56c5ff572f604b1c61625e23c2d75102f5b3ddb24b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
